# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

parameters:
  - name: target
    type: string
  - name: time
    type: string
    values:
      - morning
      - day
      - afternoon
      - evening
      - night

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, ${{ parameters.target }}! Have a nice ${{ time }}
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
